variables:
  # Repo
  REPO_OWNER: "Team Goldcrest"
  REPO_PATTERN: "V3.1 CI"
  # Product
  PRODUCT: pip-apply
  # Config
  BUILD_TYPE: MAVEN
  MAVEN_IMAGE: "maven:3-openjdk-17"
  MVN_OPTS: "-DLOG_LEVEL=INFO -Dde.flapdoodle.os.override=Linux|X86_64|Oracle|Oracle_8"
  MVN_CLI_OPTS: "--batch-mode"
  PIP_APPLY_MOCKS_NAME: pip-apply-mocks
  MOCK_IMAGE: "develop"
  SERVICE_NAME: "PIP Apply Application Manager"
  GITHUB_REPO_NAME: ms-application-manager
  CI_PROJECT_NAME: ms-application-manager
  PITEST_TARGET_CLASSES: "uk.gov.dwp.health.pip.application.manager.*"
  PITEST_TARGET_TEST_CLASSES: "uk.gov.dwp.health.pip.application.manager.*"
  PITEST_EXCLUDED_TEST_CLASSES: "*.AppControllerAdviseTest,uk.gov.dwp.health.pip.application.manager.repository.*,uk.gov.dwp.health.pip.application.manager.service.RegistrationDataGetterV5Test.*"
  PITEST_EXCLUDED_CLASSES: "uk.gov.dwp.health.pip.application.manager.openapi.*"
